name: Test release
on:
  release:
    types:
      - published
jobs:
  v3-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set time zone to Europe/Helsinki
        uses: zcong1993/setup-timezone@master
        with:
          timezone: "Europe/Helsinki"
      - name: Check Tag
        id: check-tag
        run: |
          if [[ ${GITHUB_REF##*/} =~ ^202[0-9][0-1][0-9][0-3][0-9] ]]; then
              echo "Condition true"
              echo "{match}={true}" >> $GITHUB_OUTPUT
          fi
      - name: check output
        run: |
          echo "$GITHUB_OUTPUT"
      - name: check output in a different way
        run: |
          echo "$MESSAGE"
        env:
          MESSAGE: ${{join(steps.run_tests.outputs.*, '\n')}}
      - name: Should run conditionally
        if: steps.check-tag.outputs.match == 'true'
        run: |
          echo "success"
